name: Run all CI tests
on: [pull_request]

jobs:
  run_all_tests:
    runs-on: ubuntu-latest
    name: Full CI (style and tests)
    container: jcsda/docker-gnu-openmpi-dev:1.9
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: i-jedi
        submodules: recursive
    - name: Build in a bundle
      shell: bash
      run: |
        export jedi_cmake_ROOT=/opt/view
        source /opt/spack-environment/activate.sh
        cd $GITHUB_WORKSPACE
        mkdir -p Build
        cd Build
        ecbuild ../i-jedi/bundle
        make -j4
        